spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:3307/FOODWEB
    password: admin
  jpa:
    hibernate:
#      ddl-auto: update
    show-sql: 'true'
  servlet:
    multipart:
      max-file-size: 10MB

jwt:
  secretary: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb

pathFile:
  rootPath: D:\MyLord\uploadFile